name: Lint and Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.21.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@robinfinance'

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Lint
        run: yarn lint

      - name: Build React
        run: yarn build
        env:
          CI: false
